# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  proxy:
    build: ./proxy
    networks:
      - frontend

  front:
    build:
      context: .
      target: final
    networks:
      - frontend
      - api
    image: ubuntu
    volumes:
      - url/to/lib
           
  back:
    image: postgres
    volumes:
      - url/to/lib

  api:
    image: graphql
    volumes: 
      - url/to/lib

volumes:
  db_data:
    name: "recipe-data" 
    external: true
    labels:
      com.miamakes.description: "Recipe Data"
      com.miamakes.department: "Dev"
  user_data:
    external: true
    labels:
      com.miamkes.description: "DB of Hashed User Data"
      com.miamakes.department: "Dev"